version: "3.9"
services:
  coletor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - iot

  sensor:
    build:
      context: .
      dockerfile: Dockerfile
    command: python sensor.py
    depends_on:
      - coletor
    networks:
      - iot

networks:
  iot:
